### ISSUE TITLE
doesn't work(((

### ISSUE THREAD

**Issue by vlplugg** [scaperot/the-BPM-detector-python#18]
this error:
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject22\TuneBot.py", line 111, in <module>
    parser.add_argument(x, required=False, help=".wav file for processing")
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1405, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1521, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positionals

**Comment by scaperot** [comment]
this works for me in Python 3.10.  It looks like you are running TuneBot.py.  I have no idea what that is.  =). The syntax should work for python.  See here: https://docs.python.org/3/library/argparse.html
